version: "3.5"
services:
  spring_boot:
    image: jagaldol/behind-fitness-server-spring_boot
    container_name: fitness-server
    ports:
      - "8082:8080"
    depends_on:
      - mysql
      - redis
    environment:
      TZ: "Asia/Seoul"
    env_file:
      - .env
  mysql:
    image: mysql:8.0
    container_name: fitness-mysql
    ports:
      - "3307:3306"
    environment:
      - TZ=Asia/Seoul
    env_file:
      - .mysql.env
    volumes:
      - /opt/behind/fitness/mysql:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    command:
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
  redis:
    image: redis:6.2
    container_name: fitness-redis
    ports:
      - "6380:6379"
