version: '3.8'

services:
  backend:
    image: jagaldol/behind-fitness-server-spring_boot:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_DATA_REDIS_HOST: redis
      TZ: Asia/Seoul
      TOKEN_SECRET: "fitness"

  redis:
    image: redis:6.2
    container_name: redis
    ports:
      - "6379:6379"
