version: "3.5"
services:
  mysql:
    image: mysql:8.0
    container_name: fintess-mysql
    ports:
      - "3308:3306"
    environment:
      - TZ=Asia/Seoul
    env_file: .mysql.env
    volumes:
      - /opt/mysql:/var/lib/mysql
  redis:
    image: redis:6.2
    container_name: fitness-redis
    ports:
      - "6380:6379"
