name: Deploy on AWS EC2 with SSH Connection

on:
  workflow_dispatch:
#   push:
#     branches:
#       - 'main'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_IP }}
          username: ${{ secrets.REMOTE_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: 22
          script: |
            cd behind/behind-fitness-server/
            git pull
            docker-compose up -d